NUMPY ONE DIMENSIONAL ARRAY :

In [1]:
import numpy as np
a = [1, 2, 3, 4, 5]
b = np.array(a)
print(b)

print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [15]:
import numpy as np
myarr = np.array([1, 2, 3, 4, 5],np.int64)
myarr1 = np.array([[1, 2, 3, 4, 5]],np.int64)
myarr

array([1, 2, 3, 4, 5], dtype=int64)

In [16]:
import numpy as np
myarr = np.array([1, 2, 3, 4, 5], np.int64)
myarr1 = np.array([[1, 2, 3, 4, 5]], np.int64)
myarr1[0,1]

2

In [17]:
import numpy as np
myarr = np.array([1, 2, 3, 4, 5], np.int64)
myarr1 = np.array([[1, 2, 3, 4, 5]], np.int64)
myarr1.shape

(1, 5)

In [18]:
import numpy as np
myarr = np.array([1, 2, 3, 4, 5], np.int64)
myarr.dtype


dtype('int64')

In [24]:
import numpy as np
myarr = np.array([1, 2, 3, 4, 5], np.int64)
myarr1 = np.array([[1, 2, 3, 4, 5]], np.int64)
myarr1.size

5

In [23]:
np.array({35,25,15})

array({25, 35, 15}, dtype=object)

In [5]:
import numpy as np
l=[]

for i in range(1,5):
    int_1=int(input("Enter :"))
    l.append(int_1)
    
print(np.array(l))
    

['5' '3' '6' '2']


In [22]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
lspace=np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [4]:
emp=np.empty((4,6))
emp

array([[9.87056696e-312, 6.76869935e-322, 0.00000000e+000,
        0.00000000e+000, 9.86728043e-312, 5.30276956e+180],
       [6.00736842e-067, 3.88580808e+097, 4.08824355e-033,
        3.24723137e+126, 4.25223142e+180, 7.48543529e+247],
       [2.32363010e+251, 6.11130817e+223, 2.59903818e-144,
        4.27557038e-033, 2.14330294e+184, 7.73683244e-091],
       [1.19023871e-047, 2.59027904e-144, 1.16442250e-028,
        9.44872517e-143, 9.87116274e-312, 2.08699386e-308]])

In [9]:
emp_like=np.empty_like(lspace)
emp

array([[9.87056696e-312, 6.76869935e-322, 0.00000000e+000,
        0.00000000e+000, 9.86728043e-312, 5.30276956e+180],
       [6.00736842e-067, 3.88580808e+097, 4.08824355e-033,
        3.24723137e+126, 4.25223142e+180, 7.48543529e+247],
       [2.32363010e+251, 6.11130817e+223, 2.59903818e-144,
        4.27557038e-033, 2.14330294e+184, 7.73683244e-091],
       [1.19023871e-047, 2.59027904e-144, 1.16442250e-028,
        9.44872517e-143, 9.87116274e-312, 2.08699386e-308]])

In [10]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [11]:
ide.shape

(45, 45)

In [12]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [14]:
arr.reshape(3,33)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [15]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [16]:
arr.shape

(99,)

In [18]:
x=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#axis=0 add elements vertically
ar.sum(axis=0)

array([12, 15, 18])

In [20]:
#axis=0 add elements horizontally
ar.sum(axis=1)


array([ 6, 15, 24])

In [21]:
#array transpose
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
ar.flat

In [23]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [24]:
ar.ndim

2

In [25]:
ar.size

9

In [26]:
#jtotal bytes consumed by array
ar.nbytes

36

In [32]:
#argmax ==> gives maximum element index
one=np.array([1,3,4,624,2])
print(one.argmax())
print(one.argmin())
print(one.argsort()) # sorting index


3
0
[0 4 1 2 3]


In [34]:
print(ar)
print(ar.argmin())
print(ar.argmax())
print(ar.argmax(axis=0)) #index
print(ar.argmax(axis=1)) # index


[[1 2 3]
 [4 5 6]
 [7 8 9]]
0
8
[2 2 2]
[2 2 2]


In [35]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
ar2=np.array([1,5,6])


In [39]:
print(ar+ar2)
print(ar*ar2)
print(ar/ar2)


[[ 2  7  9]
 [ 5 10 12]
 [ 8 13 15]]
[[ 1 10 18]
 [ 4 25 36]
 [ 7 40 54]]
[[1.  0.4 0.5]
 [4.  1.  1. ]
 [7.  1.6 1.5]]


In [40]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [42]:
ar.sum()

45

In [43]:
ar.min()

1

In [44]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [45]:
np.where(ar > 5)
type(np.where(ar>5))


tuple

In [48]:
np.count_nonzero(ar)

9

In [49]:
np.nonzero(ar)


(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

NUMPY ONE DIMENSIONAL ARRAY USER INPUT :

In [20]:
import numpy as np
a = []
n = int(input("Enter the size of thé array :"))
for i in range(n):
    val = int(input("Enter the number : "))
    a.append(val)
myarray = np.array(a)
myarray

array([1, 2, 3, 4, 5])